[versions]
agp = "8.11.1"
glideVersion = "4.16.0"
junitJupiterApi = "5.13.4"
kotlin = "2.2.0"
coreKtx = "1.16.0"
gson = "2.13.1"
kotlinTestJunit = "2.2.0"
kotlinxCoroutinesTest = "1.10.2"
ksp = "2.2.0-2.0.2"
junit = "4.13.2"
junitVersion = "1.2.1"
loggingInterceptor = "5.1.0"
mockk = "1.14.5"
roomKtx = "2.7.2"
retrofit = "3.0.0"
hilt = "2.57"
hilt-android = "2.57"
hilt-android-compiler = "2.57"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
swiperefreshlayout = "1.1.0"
shimmer = "0.5.0"
lifecycleRuntimeKtx = "2.9.2"
androidx-lifecycle-viewmodel-ktx = "2.9.2"
turbine = "1.2.1"
composeBom = "2024.10.01"
hilt-navigation-compose = "1.2.0"

[libraries]
# Common
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Life-cycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx-v270 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel-ktx" }

# Swipe Refresh
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }

# Shimmer
com-facebook-shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "shimmer"}

# Glide
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideVersion" }
github-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-android-compiler" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

#Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# Logging Interceptor
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }

# Gson
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Room
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomKtx" }
room-androidx-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomKtx" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApi" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinTestJunit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
androidx-lifecycle-runtime-testing = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "lifecycleRuntimeKtx" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

